---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
spec:
  selector:
    matchLabels:
      app: app-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
        - name: app-frontend
          image: sujaydevops/candidate-app-frontend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: candidate-app-frontend
spec:
  selector:
    app: app-frontend
  ports:
    - port: 3000
      nodePort: 30020
      protocol: TCP
      targetPort: 3000
  type: NodePort